version: "3"

volumes:
    produtosdata:
    
networks:
    frontend:
    backend:
    dbhost:
    
services:
        db-Server:
            image: "mysql:5.7"
            volumes:
             - produtosdata:/var/lib/mysql
            networks:
             - dbhost
            environment:
             - MYSQL_ROOT_PASSWORD=senhaprodutos1257
             - bind-address=0.0.0.0
             - LANG=pt_BR.UTF-8  
             - LANGUAGE=pt_BR  
             - LC_ALL=pt_BR.UTF-8 
             
        back-end-server:
            build:
                context: ./APIProduto
                dockerfile: Dockerfile
            networks:
                - dbhost
                - backend
            ports:
                - 5002:80
            environment:
                - DBHOST=db-Server
                - LANG=pt_BR.UTF-8  
                - LANGUAGE=pt_BR  
                - LC_ALL=pt_BR.UTF-8 
            depends_on:
                - db-Server
                
        front-end-server:
            build:
                context: ./WebAppProduto
                dockerfile: Dockerfile
            networks:
                - backend
                - frontend
            ports:
                - 5001:80
            environment:
                - HOST=back-end-server
                - LANG=pt_BR.UTF-8  
                - LANGUAGE=pt_BR  
                - LC_ALL=pt_BR.UTF-8 
            depends_on:
                - back-end-server